"""driver self-registration, cnic matching, declared arrival

Revision ID: 70bdc921f78f
Revises: d8c552641c1a
Create Date: 2026-08-07 07:41:24.041268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bdc921f78f'
down_revision: Union[str, Sequence[str], None] = 'd8c552641c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('guardian_cnic', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_students_guardian_cnic'), 'students', ['guardian_cnic'], unique=False)
    op.add_column('users', sa.Column('cnic', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('id_photo_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('selfie_url', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_cnic'), 'users', ['cnic'], unique=False)
    op.add_column('vehicles', sa.Column('expected_arrival', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'expected_arrival')
    op.drop_index(op.f('ix_users_cnic'), table_name='users')
    op.drop_column('users', 'selfie_url')
    op.drop_column('users', 'id_photo_url')
    op.drop_column('users', 'cnic')
    op.drop_index(op.f('ix_students_guardian_cnic'), table_name='students')
    op.drop_column('students', 'guardian_cnic')
    # ### end Alembic commands ###
